import type { Metadata } from "next";

export const siteConfig: Metadata = {
  title: "Abhiksha Bakshi | Electronics Engineer Portfolio",
  description: "Welcome to my electronics engineering portfolio. BTech from VIT Chennai with VLSI specialization.",
  keywords: [
    "electronics-engineering",
    "vlsi",
    "semiconductor",
    "circuit-design",
    "portfolio",
    "vit-chennai",
    "electronics",
    "engineering",
    "student",
    "vlsi-design",
    "digital-circuits",
    "analog-circuits",
    "embedded-systems",
    "microelectronics",
    "signal-processing",
    "hardware-design",
    "ic-design",
    "fpga",
    "verilog",
    "vhdl",
    "cadence",
    "mentor-graphics",
    "xilinx",
    "altera",
    "eda-tools",
    "electronics-projects",
    "engineering-portfolio",
  ] as Array<string>,
  authors: {
    name: "Abhiksha Bakshi",
    url: "https://www.linkedin.com/in/abhikshabakshi2024/",
  },
} as const;
